### ISSUE TITLE
Clarification of Partitioner.directOperation

### ISSUE THREAD

**Issue by compgumby** [mizzao/meteor-partitioner#12]
I have a use case where a user enrolls in an account and gets a number of chat codes.  He can also pre-register other users as he who enrolls is the admin for the use case.  I would love for the admin to be able to register these pre-enrolled users as a member of each group, but in order to make any database modifications, he has to login as part of that group... which means if he has 3 chat codes, he must log in in each of the three groups to set up some configuration information.  Is this where the directOperation function comes into play...and how do you use it?  Do you just pass whatever function you're trying to call as a parameter and let it rip?  It's probably really simple, but a simple example on the docs would be very helpful.  

Thanks for the hard work,
Mike

**Comment by mizzao** [comment]
`directOperation` is the underlying low-level operation on the group; in order for those documents to appear in the groups you would need to manually set the `_groupId` in your queries.

I think what you're looking for is `bindGroup`, which takes a group and a function as an argument and "pretends" to run that operation as if the current context was in that group.

**Comment by compgumby** [comment]
That totally did the trick!  Thank you so much... :)

Sorry for the delay in response.  

Please keep up the great work - you're saving me a lot of trouble.
