### ISSUE TITLE
Using mongo "$ne" operator breaks partitioner on server

### ISSUE THREAD

**Issue by kristijanhusak** [mizzao/meteor-partitioner#13]
Hi,

I am creating a comment module, where people can mention each other, and receive notifications when mentioned. For that I fetch all users except the currently logged user to allow showing mention autocomplete. Code for that looks like this:

```javascript
  return Users.find({
    _id: {$ne: Meteor.userId()}
  }).fetch().map(function(user) {
    return {
      id: user._id,
      name: user.getNickname(),
      email: user.profile.email
    };
  });
```

On the client, I get proper results, but on the server, users from all groups are fetched. When i remove `$ne` part, and use only `Users.find()`, everything works fine on both client and server.

I haven't tested other operators, since this is the only one i need at the moment. Do you know what's happening here? Thanks.

Edit: I also tried `{$not: {$in: [Meteor.userId()]}}`, but it's not working.

**Comment by mizzao** [comment]
Yeah, this seems to be the same issue as #4. I will fix this shortly, thanks for the report.

**Comment by mizzao** [comment]
Can you try the original `{_id: {$ne: Meteor.userId()} }` with `mizzao:partitioner@0.5.7`, which I just released, and tell me if it works as intended now?

Thanks!

**Comment by kristijanhusak** [comment]
@mizzao it works, thanks!

**Comment by mizzao** [comment]
Hi @kristijanhusak,

I just realized that this change may break some other things such as user login methods because they use `_id` fields with object selectors, sometimes modified by collection hooks, and then a partitioner error is thrown.

If you see any random errors when users log in, this may be the cause. I'm currently thinking about how to deal with it.

**Comment by kristijanhusak** [comment]
HI @mizzao ,

I just started writing some cucumber tests using Chimp, with help of https://github.com/xolvio/automated-testing-best-practices . I'm using [this code](https://github.com/xolvio/automated-testing-best-practices/blob/master/tests/features/step_definitions/domain/support/fixtures/account-holder-fixtures.js#L10) to log in user to server. Only difference is that i use email instead of username (Don't have usernames in my app):
```js
server.call('login', {
  user: {email: accountHolder.email},
  password: this.DEFAULT_PASSWORD
});
```
At that point, i get an error `Exception while invoking method 'login' TypeError: Cannot read property 'admin' of undefined` that is triggered in [here](https://github.com/mizzao/meteor-partitioner/blob/master/grouping.coffee#L118). `userId` from `userFindHook` is properly defined, but `Meteor.users.findOne(userId)` on [this line](https://github.com/mizzao/meteor-partitioner/blob/master/grouping.coffee#L115) returns undefined for some reason. Do you know why?

I noticed that you have added `selector?.username` to the `isDirectUserSelector` check. Is that added only to avoid performance issues or there is another reason?

As soon as I added this to the `isDirectUserSelector`, my tests passed without any problem:
```coffee
    _.isString(selector) or
      _.isString(selector?._id) or
      _.isString(selector?.username) or
      _.isString(selector?['emails.address']) or # this is added
     (_.isObject(selector?._id) and selector._id.$in?)
```
This is because `server.login` with email uses that `emails.address` query when trying to log in, and this returns true in that case. Is username added for same reason?

**Comment by mizzao** [comment]
That makes sense. `_id`, `username`, and `emails.address` are all unique identifiers for users, and I believe the purpose of `isDirectUserSelector` is to bypass any hooks for direct user queries so as to not break various accounts-related features. It ignores the partitioning, but then again most partition queries aren't for single users and this package is not intended to be a secure multi-tenant solution.

(Sorry for the really delayed response. I'd be totally happy if you pulled your tests and other updates into master and published a new version of the package.)
