### ISSUE TITLE
Problems with Collections.allow

### ISSUE THREAD

**Issue by skemb321** [mizzao/meteor-partitioner#17]
Hello Mizzao,

I have found out that inserts doesn't work with Partitioned Collections that have allow/deny options. Can you help me with this one, pls?

**Comment by mizzao** [comment]
What do you mean by "doesn't work" ?

**Comment by skemb321** [comment]
I mean, the insert call from the client is denied despite of having `Collection.allow({insert: true});`

**Comment by mizzao** [comment]
What is the error you are getting when the insert is denied? I think your code is wrong, it should be

```
Collection.allow({insert: function() { return true; } });
```

Please read the docs: https://docs.meteor.com/#/full/allow
