### ISSUE TITLE
groupId not set for documents created via upsert

### ISSUE THREAD

**Issue by hockeyj85** [mizzao/meteor-partitioner#18]
There's no mention of meteor-partitioner handling upserts on the `README.md`, should upserted documents that result in a document being created in the collection have a groupId set?

# Reproduce

Use [`collection.upsert()`](http://docs.meteor.com/#/full/upsert) to insert a document in to a Mongo collection inside of a `Partitioner.bindGroup()`.

# Result

The document that was inserted has no `_groupId` set.

# Expected

If an upsert results in an insert, I would expect it to have a groupId.

**Comment by hockeyj85** [comment]
Disregard this, I dun goofed. If you follow the reproduce step exactly the result is the expected behavior.

**Comment by mizzao** [comment]
You sure? I think in 0.8.0 of collection hooks this might well be a problem.

**Comment by hockeyj85** [comment]
We're using collection hooks 0.7.13, meteor-partitioner 0.5.4  in the project where this effect was produced, but It was due to human error - I mistakenly passed a function into bindGroup instead of a string for the groupId and it resulted in not setting the _groupId for the stored document (though the document was still stored).

That's not to say that 0.8.0 this issue may not exist.
