### ISSUE TITLE
Nothing returned from subscription

### ISSUE THREAD

**Issue by c316** [mizzao/meteor-partitioner#23]
I created a document and I see it in the colleciton
```
{
    "_id" : "LzqJZPC5TiNRmJC5H",
    "createdAt" : "2016-09-23T15:54:28.550Z",
    "name" : "Bechard",
    "_groupId" : "7JByc8A2ahr4gwerf"
}
```

If I use ```Partitioner.bindGroup("7JByc8A2ahr4gwerf", function(){console.log(Families.find().fetch())})
``` in the Meteor shell and I see this document listed. I get the same document if I use the bindUserGroup method

However, if I subscribe like this
```
Template.Families.onCreated(function () {
  this.autorun(()=> {
    let group = Partitioner.group();
    Meteor.subscribe('families', group);
  });
});
```

Using this publish method
```
Meteor.publish({
  'families'(){
    return Families.find();
  },
});
```

I get nothing on the client side. Is there a way to debug this?

**Comment by c316** [comment]
Also, if I remove this package I get the document on the client side without a problem.

**Comment by mizzao** [comment]
Um...is that the right syntax for `publish`?

**Comment by c316** [comment]
Hmm... apparently not, I've been using that syntax for a while, never had any trouble with it. Once I put the publish into the proper format it seems to be working just fine. 

Thanks
