### ISSUE TITLE
Queries ignore group when a complex _id is specified

### ISSUE THREAD

**Issue by nwweber** [mizzao/meteor-partitioner#4]
Problem: When updating a partitioned collection all matching documents are updated across all groups, not just the current one.

Setting: I have a collection of documents. Each document contains a story and whether this is the currently featured story (of which there should only be one per group). This collection is partitioned by group.

After setting featured: true on the new story, I update the old ones by setting featured: false, using multi: true (this should be unnecessary, but you never know with outside users).

This second call to update, setting featured: false, then affects all matching documents in the collection, independent of _groupId.

I have tried explicitly wrapping the whole function in Partitioner.bindGroup (which should not be necessary) but this does not have an effect.

See the code below

Any input is appreciated. Thanks for the great work so far! :)

Code:

(this is a function in `Meteor.methods` which is called by the user with `Meteor.call('make_featured', story_id)`

```javascript
make_featured: function (story_id) {
        if (!(Roles.userIsInRole(this.userId, ["group-admin"]))) {
            throw new Meteor.Error('not_ga', 'You have to be a group admin to do this');
        }
        if (!(this.userId)) {
            throw new Meteor.Error('not_logged_in', 'Not logged in');
        }
        if (!(story_id)) {
            throw new Meteor.Error('no_id', 'No story id has been provided');
        }
        var nr_un_featured;
        var nr_featured;

        console.log(Partitioner.group())
        nr_featured = PublicStories.update(
            {
                _id: story_id
            },
            {
                $set: {
                    featured: true
                }
            }
        );

        // at this point we expect to have updated exactly one story
        // if this number is different, something is wrong
        if (!(nr_featured === 1)) {
            throw new Meteor.Error('wrong_update_number', 'Updated ' + nr_featured + ' documents instead of 1')
        }
        // un-feature other documents
        nr_un_featured = PublicStories.update(
            {
                _id: {$ne: story_id},
                featured: true
            },
            {
                $set: {
                    featured: false
                }
            },
            {
                multi: true
            }
        );
        if (!(nr_un_featured === 1)) {
            throw new Meteor.Error('wrong_unfeature_number', 'Unfeatured ' + nr_un_featured + ' documents instead of 1')
        }


    }
```

**Comment by mizzao** [comment]
This should be (mostly) fixed in v0.5.7 (except https://github.com/mizzao/meteor-partitioner/issues/9#issuecomment-133058993).
